---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mubarek-prime-video-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mubarek-prime-video
  template:
    metadata:
      labels:
        app: mubarek-prime-video
    spec:
      containers:
      - name: mubarek-prime-video-container
        image: maol2ga/amazon-prime-video:latest   # âœ… your DockerHub repo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mubarek-prime-video-service
spec:
  type: LoadBalancer
  selector:
    app: mubarek-prime-video
  ports:
  - port: 80
    targetPort: 3000

